"""Initial migration

Revision ID: 6592e8625224
Revises: 
Create Date: 2026-05-21 17:50:54.977001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6592e8625224'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=10), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city', 'country', name='uix_city_country')
    )
    op.create_index(op.f('ix_locations_city'), 'locations', ['city'], unique=False)
    op.create_table('pipeline_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('records_extracted', sa.Integer(), nullable=True),
    sa.Column('records_loaded', sa.Integer(), nullable=True),
    sa.Column('records_rejected', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('api_request_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_runs_started_at'), 'pipeline_runs', ['started_at'], unique=False)
    op.create_table('weather_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_run_id', sa.UUID(), nullable=False),
    sa.Column('temp_avg_c', sa.Float(), nullable=True),
    sa.Column('temp_min_c', sa.Float(), nullable=True),
    sa.Column('temp_max_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Integer(), nullable=True),
    sa.Column('pressure_hpa', sa.Integer(), nullable=True),
    sa.Column('wind_speed_kmh', sa.Float(), nullable=True),
    sa.Column('wind_direction_deg', sa.Integer(), nullable=True),
    sa.Column('wind_direction', sa.Enum('N', 'NNE', 'NE', 'ENE', 'E', 'ESE', 'SE', 'SSE', 'S', 'SSW', 'SW', 'WSW', 'W', 'WNW', 'NW', 'NNW', name='wind_direction_enum'), nullable=True),
    sa.Column('wind_gust_kmh', sa.Float(), nullable=True),
    sa.Column('rain_tomorrow', sa.Boolean(), nullable=True),
    sa.Column('precipitation_mm', sa.Float(), nullable=True),
    sa.Column('weather_description', sa.String(), nullable=True),
    sa.Column('observation_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'observation_timestamp', name='uix_loc_obs_time')
    )
    op.create_index(op.f('ix_weather_readings_observation_timestamp'), 'weather_readings', ['observation_timestamp'], unique=False)
    op.create_index(op.f('ix_weather_readings_pipeline_run_id'), 'weather_readings', ['pipeline_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weather_readings_pipeline_run_id'), table_name='weather_readings')
    op.drop_index(op.f('ix_weather_readings_observation_timestamp'), table_name='weather_readings')
    op.drop_table('weather_readings')
    op.drop_index(op.f('ix_pipeline_runs_started_at'), table_name='pipeline_runs')
    op.drop_table('pipeline_runs')
    op.drop_index(op.f('ix_locations_city'), table_name='locations')
    op.drop_table('locations')
    # ### end Alembic commands ###
